microservice-chart: &microservice-chart
  namespace: "nodo"
  nameOverride: ""
  fullnameOverride: ""
  terminationGracePeriodSeconds: 140

  image:
    repository: pagopadcommonacr.azurecr.io/pagopamockec
    tag: "0.0.1"
    pullPolicy: Always
  readinessProbe:
    handlerType: tcpSocket
    tcpSocket:
      port: 8080
    initialDelaySeconds: 20
    periodSeconds: 10
  livenessProbe:
    handlerType: tcpSocket
    tcpSocket:
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 20
  deployment:
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
  #  serviceMonitor:
  #    create: true
  #    endpoints:
  #      - interval: 5s
  #        targetPort: 8080
  #        path: /q/metrics
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  serviceAccount:
    name: "nodo-workload-identity"
  azure:
    workloadIdentityClientId: <workload-identity-client-id-set-automatically-by-gha>
  securityContext:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - all
  resources:
    requests:
      memory: "200Mi"
      cpu: "300m"
    limits:
      memory: "512Mi"
      cpu: "400m"
  autoscaling:
    enable: false
  #    minReplica: 1
  #    maxReplica: 1
  #    pollingInterval: 10 # seconds
  #    cooldownPeriod: 50 # seconds
  #    triggers:
  #      - type: cpu
  #        metadata:
  #          type: Utilization
  #          value: "75"
  #      - type: memory
  #        metadata:
  #          type: Utilization
  #          value: "75"
  envConfig:
    TIMEOUT_DELAY: "5000"
    PPT_NODO: "/mock"
    PORT: "8080"
    CC_BANK_PRIMARY_EC: "IT96R0123454321000000012345"
    CC_BANK_SECONDARY_EC: "IT04O0100003245350008332100"
    TEST_DEBUG: "Y"
    AUX_DIGIT: "3"
  envFieldRef:
    APP_NAME: "metadata.labels['app.kubernetes.io/instance']"
    APP_VERSION: "metadata.labels['app.kubernetes.io/version']"
  envSecret:
    OTEL_EXPORTER_OTLP_HEADERS: "elastic-apm-secret-token"
  keyvault:
    name: "pagopa-d-nodo-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  tolerations:
    - key: dedicated
      operator: Equal
      value: "nodo"
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nodo
                operator: In
                values:
                  - "true"

mock-primary:
  !!merge <<: *microservice-chart
  ingress:
    create: true
    host: "weudev.nodo.internal.dev.platform.pagopa.it"
    path: /mock-ec(/|$)(.*)
    pathType: ImplementationSpecific
    servicePort: 8080
    annotations:
      nginx.ingress.kubernetes.io/proxy-read-timeout: "130"
    proxyBodySize: 100m
    rewriteTarget: /$2

mock-secondary:
  !!merge <<: *microservice-chart
  ingress:
    create: true
    host: "weudev.nodo.internal.dev.platform.pagopa.it"
    path: /mock-ec-secondary(/|$)(.*)
    pathType: ImplementationSpecific
    servicePort: 8080
    annotations:
      nginx.ingress.kubernetes.io/proxy-read-timeout: "130"
    proxyBodySize: 100m
    rewriteTarget: /$2

mock-ec-replica:
  !!merge <<: *microservice-chart
  ingress:
    create: true
    host: "weudev.nodo.internal.dev.platform.pagopa.it"
    path: /mock-ec-rep(/|$)(.*)
    pathType: ImplementationSpecific
    servicePort: 8080
    annotations:
      nginx.ingress.kubernetes.io/proxy-read-timeout: "130"
    proxyBodySize: 100m
    rewriteTarget: /$2